# netlify.toml
[build]
  base    = "fronten-car-rental"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory    = "backend-car-rental/functions"
  node_bundler = "esbuild"
