# netlify.toml
[build]
  # Build from repo root so we can install both front-end and back-end deps
  command = "npm --prefix fronten-car-rental ci && npm --prefix backend-car-rental ci && npm --prefix fronten-car-rental run build"
  publish = "fronten-car-rental/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--silent"

[functions]
  directory    = "backend-car-rental/functions"
  node_bundler = "zisi"
  # Ensure Mongoose and its MongoDB driver internals are included in the bundle
  included_files = [
    "backend-car-rental/node_modules/mongoose/**",
    "backend-car-rental/node_modules/mongodb/**"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
